CREATE TABLE mc_donalds_menu(
category varchar(100),
item varchar(100),
serving_size varchar(100),
	calories numeric,
	calories_from_fat numeric, 
	total_fat numeric,
	total_fat_daily numeric,
	saturated_fat numeric, 
	saturated_fat_daily numeric,
	trans_fat numeric,
	cholesterol numeric,
	cholesterol_daily numeric,
	sodium numeric,
	sodium_daily numeric,
	carbohydrates numeric,
	carbohydrates_daily numeric,
	dietary_fiber numeric,
	dietary_fiber_daily numeric,
	sugars numeric,
	protein numeric,
	vitamin_a_daily numeric,
	vitamin_c_daily numeric,
	calcium_daily numeric,
	iron_daily numeric
);

